version: '3.8'

services:
  myportfolio:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
    expose:
      - "5000"
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./user_conf.d:/etc/nginx/conf.d:ro
      - ./app/static:/usr/share/nginx/html/static:ro
    depends_on:
      - myportfolio

  mysql:
    image: mariadb:10.5
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase:
  nginx_secrets: 
